#!/usr/bin/env python3
"""Generate Docker-free Apptainer recipes: <kit>/environment/apptainer.native.def.

Each kit ships a Dockerfile and an apptainer.def that bootstraps FROM the locally built Docker
image (`Bootstrap: docker-daemon`), so building the .sif needs a Docker daemon. This script
translates the Dockerfile itself into Apptainer's own recipe format:

  FROM img         -> Bootstrap: docker / From: img      (pulled straight from the registry)
  ARG k=v          -> %arguments k=v + export k="{{ k }}" (override with apptainer build --build-arg k=...)
  ENV k=v          -> export in %post at the same point, and in %environment
  COPY src... dst  -> the build context is staged at /.ctx via %files; %post copies from it in order
  WORKDIR d        -> mkdir -p d && cd d
  RUN cmd          -> the same command, run by /bin/sh at the same point (non-zero exit aborts the build)

and keeps the %post / %environment / %runscript / %help of the kit's original apptainer.def.

Usage (from the repository root):  python3 tools/docker2apptainer.py [kit ...]   (default: every kit)
"""
import re
import shlex
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IGNORED = {"USER", "LABEL", "EXPOSE", "CMD", "ENTRYPOINT", "SHELL", "VOLUME", "HEALTHCHECK", "STOPSIGNAL"}


def logical_lines(text):
    """Dockerfile instructions with continuation lines joined (newlines kept for RUN bodies)."""
    out, buf = [], []
    for line in text.splitlines():
        if not buf and (not line.strip() or line.lstrip().startswith("#")):
            continue
        if buf and line.lstrip().startswith("#"):  # comment lines inside a continued instruction
            continue
        buf.append(line)
        if not line.rstrip().endswith("\\"):
            out.append("\n".join(buf))
            buf = []
    if buf:
        out.append("\n".join(buf))
    return out


def parse_kv(rest):
    """ENV / ARG bodies: `k=v k2=v2` or the legacy `k v` form."""
    flat = re.sub(r"\\\n", " ", rest).strip()
    toks = shlex.split(flat, posix=True)
    if toks and "=" not in toks[0]:
        return [(toks[0], " ".join(toks[1:]) if len(toks) > 1 else None)]
    return [(k, v) for k, _, v in (t.partition("=") for t in toks)] if toks else []


def dq(v):
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"').replace("`", "\\`") + '"'


def sections(def_text):
    """Section name -> body of an apptainer.def (header lines dropped)."""
    secs, cur = {}, None
    for line in def_text.splitlines():
        m = re.match(r"^%(\w+)\s*$", line)
        if m:
            cur = m.group(1)
            secs[cur] = []
        elif cur:
            secs[cur].append(line)
    return {k: "\n".join(v).rstrip() for k, v in secs.items()}


def convert(kit):
    df = ROOT / kit / "environment" / "Dockerfile"
    orig = ROOT / kit / "environment" / "apptainer.def"
    instrs = logical_lines(df.read_text())
    base, args, post, envs, ctx_roots, n = None, [], [], [], set(), 0

    for ins in instrs:
        op, _, rest = ins.partition(" ")
        op = op.upper()
        if op == "FROM":
            if base:
                raise SystemExit(f"{kit}: multi-stage Dockerfile not supported")
            base = rest.split()[0]
        elif op == "ARG":
            for k, v in parse_kv(rest):
                if k not in [a for a, _ in args]:
                    args.append((k, v or ""))
                post.append(f'export {k}="{{{{ {k} }}}}"')
        elif op == "ENV":
            for k, v in parse_kv(rest):
                post.append(f"export {k}={dq(v)}")
                envs.append(f"export {k}={dq(v)}")
        elif op == "WORKDIR":
            post.append(f"mkdir -p {rest.strip()} && cd {rest.strip()}")
        elif op in ("COPY", "ADD"):
            toks = shlex.split(re.sub(r"\\\n", " ", rest))
            if any(t.startswith("--") for t in toks):
                raise SystemExit(f"{kit}: COPY flags not supported: {ins}")
            *srcs, dst = toks
            for s in srcs:
                ctx_roots.add(s.split("/")[0])
            post.append("_copy " + " ".join(f"/.ctx/{s}" for s in srcs) + f" {dst}")
        elif op == "RUN":
            n += 1
            body = rest
            post.append(f"cat > /tmp/.run{n}.sh <<'__DOCKER_RUN_{n}__'\n{body}\n__DOCKER_RUN_{n}__\n"
                        f"/bin/sh /tmp/.run{n}.sh || {{ echo 'RUN step {n} failed' >&2; exit 1; }}; rm -f /tmp/.run{n}.sh")
        elif op in IGNORED:
            post.append(f"# (ignored) {ins.splitlines()[0]}")
        else:
            raise SystemExit(f"{kit}: unsupported instruction {op}")

    secs = sections(orig.read_text()) if orig.exists() else {}
    header_comment = [l for l in (orig.read_text().splitlines() if orig.exists() else []) if l.startswith("#")]

    o = []
    o.append(f"# GENERATED by tools/docker2apptainer.py from {kit}/environment/Dockerfile — native Apptainer build, no Docker daemon needed.")
    o.append("# Build from the repository root (the directory holding common/ and the kits):")
    o.append(f"#   bash tools/build_sif.sh {kit}          # or: mkdir -p _jitcache && apptainer build [--fakeroot] {kit}.sif {kit}/environment/apptainer.native.def")
    o.append("# Build arguments of the Dockerfile are Apptainer build args: apptainer build --build-arg NAME=value ...")
    o.append("# Everything below the original header works exactly as documented for apptainer.def:")
    o += header_comment
    o.append(f"Bootstrap: docker\nFrom: {base}\n")
    if args:
        o.append("%arguments")
        o += [f"    {k}={v}" for k, v in args]
        o.append("")
    o.append("%files")
    for r in sorted(ctx_roots):
        o.append(f"    {r} /.ctx/{r}")
    o.append("")
    o.append("%post")
    o.append("    # the base image's Docker ENV (PATH, CUDA vars, MAMBA_ROOT_PREFIX, ...) as a Docker RUN would see it")
    o.append("    [ -f /.singularity.d/env/10-docker2singularity.sh ] && . /.singularity.d/env/10-docker2singularity.sh")
    o.append("    export HOME=/root DEBIAN_FRONTEND=noninteractive")
    o.append("    cd /")
    o.append(_COPY_FN)
    for p in post:
        o += ["    " + l if l else "" for l in p.split("\n")] if not p.startswith("cat > ") else _indent_heredoc(p)
    o.append("    cd / && rm -rf /.ctx")
    if secs.get("post"):
        o.append("    # --- from the original apptainer.def")
        o.append(secs["post"])
    o.append("")
    o.append("%environment")
    o += ["    " + e for e in envs]
    if secs.get("environment"):
        o.append(secs["environment"])
    o.append("")
    for s in ("runscript", "help"):
        if secs.get(s):
            o.append(f"%{s}\n{secs[s]}\n")
    out = ROOT / kit / "environment" / "apptainer.native.def"
    out.write_text("\n".join(o) + "\n")
    return out


def _indent_heredoc(p):
    # keep the RUN body verbatim (heredoc content must not gain indentation-sensitive changes; the terminator must be unindented)
    lines = p.split("\n")
    return ["    " + lines[0]] + lines[1:-2] + [lines[-2], "    " + lines[-1]]


_COPY_FN = r"""    # Docker COPY semantics: a directory source copies its contents; several sources or a trailing / mean "into dst/";
    # a glob that matches nothing is skipped (the Dockerfiles use `_jitcache/x-*-jit.ta[r]` for optional files)
    _copy() {
        for _dst; do :; done; _n=$(($# - 1)); _i=0; _srcs=""
        for _a in "$@"; do _i=$((_i + 1)); [ $_i -le $_n ] || break
            for _m in $_a; do [ -e "$_m" ] && _srcs="$_srcs $_m"; done; done
        _into=0; case "$_dst" in */) _into=1;; esac; [ $_n -gt 1 ] && _into=1
        for _s in $_srcs; do
            if [ -d "$_s" ]; then mkdir -p "$_dst" && cp -a "$_s"/. "$_dst"/
            elif [ $_into = 1 ]; then mkdir -p "$_dst" && cp -a "$_s" "$_dst"/
            else mkdir -p "$(dirname "$_dst")" && cp -a "$_s" "$_dst"; fi
        done
    }"""


def main():
    kits = sys.argv[1:] or sorted(p.parent.parent.name for p in ROOT.glob("*/environment/Dockerfile"))
    for k in kits:
        print(convert(k).relative_to(ROOT))


if __name__ == "__main__":
    main()
